const brands = [
  "Zara",
  "H&M",
  "Mango",
  "Asos",
  "Topshop",
  "Uniqlo",
  "Levi's",
  "Nike",
  "Adidas",
  "Puma",
  "Reebok",
  "Converse",
  "New Balance",
  "Gucci",
  "Prada",
  "Chanel",
  "Louis Vuitton",
  "Dior",
  "Saint Laurent",
  "Balenciaga",
  "Givenchy",
  "Off-White",
  "Acne Studios",
  "Comme des Garçons",
  "Balmain",
  "Versace",
  "Fendi",
  "Kenzo",
  "Burberry",
  "Ralph Lauren",
  "Tommy Hilfiger",
  "Calvin Klein",
  "Diesel",
  "Guess",
  "G-Star Raw",
  "Lacoste",
  "The North Face",
  "Columbia",
  "Patagonia",
  "Timberland",
  "Dr. Martens",
  "UGG",
  "Clarks",
  "Arket",
  "Bershka",
  "Stradivarius",
  "Pull & Bear",
  "Massimo Dutti",
  "COS",
  "& Other Stories",
  "Sandro",
  "Maje",
  "Claudie Pierlot",
  "Sézane",
  "Ba&sh",
  "Isabel Marant",
  "Chloé",
  "Celine",
  "Hermès",
  "Bottega Veneta",
  "Alexander McQueen",
  "Marc Jacobs",
  "Proenza Schouler",
  "Stella McCartney",
  "Lanvin",
  "Valentino",
  "Moschino",
  "Michael Kors",
  "Coach",
  "Fossil",
  "American Eagle",
  "Abercrombie & Fitch",
  "Hollister",
  "The Kooples",
  "Carhartt",
  "Dickies",
  "Vero Moda",
  "Mango Man",
  "Jack & Jones",
  "Pullin",
  "Scotch & Soda",
  "Ted Baker",
  "AllSaints",
  "Barbour",
  "Canada Goose",
  "The Kooples Sport",
  "Nike SB",
  "Jordan",
  "Vans Vault",
  "Maison Margiela",
  "Rick Owens",
  "Yohji Yamamoto",
  "Raf Simons",
  "Amiri",
  "Stone Island",
  "CP Company",
  "Officine Generale",
  "A.P.C.",
  "Norse Projects",
  "Our Legacy",
  "Visvim",
  "Patagonia Provisions",
  "Veja",
  "Common Projects",
  "Axel Arigato",
  "Saucony",
  "Onitsuka Tiger",
  "Clarks Originals",
  "Red Wing",
  "Wolverine",
  "Grenson",
  "Tara Jarmon",
  "Gerard Darel",
  "Zadig & Voltaire",
  "Sessùn",
  "Vanessa Bruno",
  "Aigle",
  "Agnès b",
  "Armor-Lux",
  "Berluti",
  "Bonpoint",
  "Cerruti 1881",
  "Courrèges",
  "Eric Bompard",
  "Fusalp",
  "Iro",
  "Isabel Marant Étoile",
  "Jacquemus",
  "Jonak",
  "K-Way",
  "Lacoste",
  "Le Coq Sportif",
  "Longchamp",
  "Maison Kitsuné",
  "Olympia Le-Tan",
  "Paraboot",
  "Petit Bateau",
  "Repetto",
  "Sandro Homme",
  "Sessùn Homme",
  "Sonia Rykiel",
  "Zilli",
  "Shein",
  "AliExpress",
  "Oysho",
  "Bimba y Lola",
  "Camper",
  "Pikolinos",
  "Martinelli",
  "Hispanitas",
  "Wonders",
  "El Ganso",
  "Scalpers",
  "Dockers",
  "Superdry",
  "Fred Perry",
  "Paul Smith",
  "Hunter",
  "Joules",
  "French Connection",
  "Mango Kids",
  "Jacadi",
  "Sergent Major",
  "Kiabi",
  "La Redoute",
  "Cyrillus",
  "Tape à l'oeil",
  "DPAM",
  "Mellow Yellow",
  "Minelli",
  "André",
  "Eram",
  "San Marina",
  "Cosmoparis",
  "Kookai",
  "Naf Naf",
  "Carven",
  "Anne Fontaine",
  "Chantelle",
  "Simone Perele",
  "Princesse tam.tam",
  "DIM",
  "Le Slip Français",
  "Saint James",
  "Sandro Ferrone",
  "Intimissimi",
  "Calzedonia",
  "Tezenis",
  "Sisley",
  "Benetton",
  "Liu Jo",
  "Twinset",
  "PINKO",
  "Brandy Melville",
  "Golden Goose",
  "Hogan",
  "Tod's",
  "Church's",
  "Sergio Rossi",
  "Giuseppe Zanotti",
  "Pollini",
  "Marni",
  "Missoni",
  "Roberto Cavalli",
  "Alberta Ferretti",
  "Emilio Pucci",
  "MSGM",
  "Diesel",
  "Fiorucci",
  "Frankie Morello",
  "Pinko",
  "Roy Rogers",
  "Paul & Shark",
  "Frankie Morello",
  "Boggi Milano",
  "Harmont & Blaine",
  "Navigare",
  "Boggi Milano",
  "Herno",
  "Fay",
  "Moncler",
  "Colmar",
  "Peuterey",
  "Blauer",
  "Kappa",
  "Macron",
  "Lotto",
  "Diadora",
  "Superga",
  "Pantofola d'Oro",
  "Freddy",
  "Deha",
  "Ellesse",
  "Sundek",
  "Altea",
  "Aspesi",
  "Fila",
  "Fila Vintage",
  "Henry Cotton's",
  "Jeckerson",
  "Roy Roger's",
  "Save The Duck",
  "Stone Island Shadow Project",
  "Sun68",
  "Tecnica",
  "Woolrich",
  "C.P. Company",
  "Dondup",
  "Duvetica",
  "Herno",
  "Jil Sander",
  "Laneus",
  "Manila Grace",
  "P.A.R.O.S.H",
  "Peuterey",
  "Pinko",
  "Seventy",
  "8pm",
  "Le Coeur Twin-Set Simona Barbieri",
  "Jeckerson",
  "Anthropologie",
  "Athleta",
  "Banana Republic",
  "BCBGMAXAZRIA",
  "Billabong",
  "Brooks Brothers",
  "Calvin Klein Underwear",
  "Champion",
  "Charlotte Russe",
  "Club Monaco",
  "Columbia Sportswear",
  "Crocs",
  "Current/Elliott",
  "DKNY",
  "Eddie Bauer",
  "Forever 21",
  "Free People",
  "GANT",
  "Gap",
  "Gilly Hicks",
  "Hollister Co.",
  "J. Crew",
  "J. Jill",
  "Janie and Jack",
  "Juicy Couture",
  "Kate Spade",
  "L.L.Bean",
  "Lands' End",
  "Lululemon",
  "Madewell",
  "Marc by Marc Jacobs",
  "Nasty Gal",
  "Old Navy",
  "Paige",
  "Rag & Bone",
  "Roxy",
  "Spanx",
  "Splendid",
  "The Limited",
  "Theory",
  "Tory Burch",
  "Under Armour",
  "Vince Camuto",
  "White House Black Market",
  "Wildfox",
  "décathlon",
  "decathlon",
];
export default brands;
