import type { Color } from "../../../../../common/types/types";

const colorsVinted: Record<Color, string> = {
  colorBlack: "1",
  colorGrey: "3",
  colorWhite: "12",
  colorCreme: "20",
  colorBeige: "4",
  colorAbricot: "21",
  colorOrange: "11",
  colorCoral: "22",
  colorRed: "7",
  colorBurgundy: "23",
  colorPink: "5",
  colorRose: "24",
  colorPurple: "6",
  colorLilac: "25",
  colorLightBlue: "26",
  colorBlue: "9",
  colorNavy: "27",
  colorTurquoise: "17",
  colorMint: "30",
  colorGreen: "10",
  colorDarkGreen: "28",
  colorKhaki: "16",
  colorBrown: "2",
  colorMustard: "29",
  colorYellow: "8",
  colorSilver: "13",
  colorGold: "14",
  colorMulticolor: "15",
};

const colorsLeboncoin: Record<Color, string> = {
  colorBlack: "noir",
  colorSilver: "argent",
  colorBeige: "beige",
  colorWhite: "blanc",
  colorBlue: "bleu",
  colorCreme: "creme",
  colorGold: "dore",
  colorGrey: "gris",
  colorYellow: "jaune",
  colorKhaki: "kaki",
  colorNavy: "marine",
  colorBrown: "marron",
  colorMulticolor: "multicolore",
  colorOrange: "orange",
  colorPink: "rose%2Clavande",
  colorRed: "rouge",
  colorGreen: "vert",
  colorPurple: "violet",
  colorAbricot: "orange",
  colorCoral: "orange",
  colorRose: "rose",
  colorLilac: "lavande",
  colorLightBlue: "bleu",
  colorTurquoise: "bleu",
  colorMint: "vert",
  colorDarkGreen: "vert",
  colorBurgundy: "rouge",
  colorMustard: "jaune",
};

export { colorsLeboncoin, colorsVinted };
