import type { Color } from "../../../../../common/types/types";



const colorsVinted: Record<Color, string>={
    black: '1',
    grey: '3',
    white: '12',
    creme: '20',
    beige: '4',
    abricot: '21',
    orange: '11',
    coral: '22',
    red:'7',
    burgundy: '23',
    pink:'5',
    rose: '24',
    purple: '6',
    lilac: '25',
    LightBlue: '26',
    blue: '9',
    navy: '27',
    turquoise: '17',
    mint: '30',
    green: '10',
    darkGreen: '28',
    khaki: '16',
    brown: '2',
    mustard: '29',
    yellow: '8',
    silver: '13',
    gold: '14',
    multicolor: '15'
} 
const colorsLeboncoin: Record<Color, string>={
    black: 'noir',
    silver: 'argent',
    beige: 'beige',
    white: 'blanc',
    blue: 'bleu',
    creme: 'creme',
    gold: 'dore',
    grey: 'gris',
    yellow: 'jaune',
    khaki: 'kaki',
    navy: 'marine',
    brown: 'marron',
    multicolor: 'multicolore',
    orange: 'orange',
    pink: 'rose%2Clavande',
    red: 'rouge',
    green: 'vert',
    purple: 'violet',
    abricot: 'orange',
    coral: 'orange',
    rose: 'rose',
    lilac: 'lavande',
    LightBlue: 'bleu',
    turquoise: 'bleu',
    mint: 'vert',
    darkGreen: 'vert',
    burgundy: 'rouge',
    mustard: 'jaune',
    }
export { colorsLeboncoin, colorsVinted}